version: '3.9'
services:
  amwinterhalter-site:
    container_name: amwinterhalter_site
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5085"
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - amwinterhalter-site
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
